### ISSUE TITLE
steamos-backgrounds is needed by steamos-session, but not included in your repository.

### ISSUE THREAD

**Issue by audreytoskin** [negativo17/steamos-backgrounds#1]
I'm running Fedora 24 (64-bit) with Nouveau drivers for a GeForce 9600 GT. I've added the free and nonfree RPM Fusion repos, and your Steam repo.

When I try to install the Steam packages by running:
`sudo dnf install -y  steam  steamos-session  steamos-modeswitch-inhibitor.i686  libvdpau.i686  dkms-xpad  kernel-devel  libtxc_dxtn`
 I get this error message:

> Error: nothing provides steamos-backgrounds needed by steamos-session-1.33-1.fc24.noarch

**Comment by scaronni** [comment]
Sorry, broken upload. Re-generating the repository now.
Thanks for notifying!

**Comment by scaronni** [comment]
Oh, btw, if you want there's this "hidden" repository:

http://negativo17.org/repos/fedora-nvidia-340.repo

I don't have the hardware, so I maintain it based on user feedback (many users are happy so far).

**Comment by audreytoskin** [comment]
Does this hidden repository provide patches for Nouveau or for the proprietary Nvidia drivers? I'd heard about how the open source Nouveau drivers have gotten much better over the years, so I thought I might be able to get away with using the open source version... Funny enough, when I tested in Portal 2, the graphics had rendering bugs (models flickering, weird lines sticking out of walls), rather than simply rendering too slowly. So a few days ago I went back to using the proprietary drivers after all :/

**Comment by scaronni** [comment]
It's just for the old 340.xx series of proprietary drivers.
Unfortunately, Nouveau is enough only for open source engine games (dhewm3, etc.).
